# applicationset deploying the python-app helm chart from our own harness
# code repo (gitops_sample, see code_repo.tf) to every cluster registered
# against the project's gitops agent, using the built-in cluster generator.

# harness scopes argocd projects to a harness project explicitly; map the
# argocd "default" project (used by the cluster resources and appset below)
# to this project so the applicationset is allowed to target it.
resource "harness_platform_gitops_app_project_mapping" "default" {
  org_id            = var.org_id
  project_id        = harness_platform_project.this.id
  agent_id          = var.gitops_agent_id
  argo_project_name = "default"
}

# the argocd "default" AppProject isn't created automatically by this chart,
# so create it explicitly, wide open (matches upstream argocd's built-in
# default project) so the example apps below can deploy anywhere.
resource "harness_platform_gitops_app_project" "default" {
  org_id     = var.org_id
  project_id = harness_platform_project.this.id
  agent_id   = var.gitops_agent_id
  upsert     = true

  project {
    metadata {
      name      = "default"
      namespace = "gitops-agent"
    }
    spec {
      source_repos = ["*"]
      destinations {
        server    = "*"
        namespace = "*"
      }
      cluster_resource_whitelist {
        group = "*"
        kind  = "Namespace"
      }
    }
  }
}

# service/environment linkage for the appset below - required so the
# standard GitOps CD stage (Deployment + GitOpsSync) can target the apps
# this appset generates. the harness.io/serviceRef + envRef labels on the
# appset template propagate to every child application automatically.
resource "harness_platform_service" "python_app_gitops" {
  org_id     = var.org_id
  project_id = harness_platform_project.this.id

  identifier  = "python_app_gitops"
  name        = "python app gitops"
  description = "service reference for the appset-managed python-app example"

  yaml = <<-EOT
service:
  name: python app gitops
  identifier: python_app_gitops
  orgIdentifier: ${var.org_id}
  projectIdentifier: ${harness_platform_project.this.id}
  serviceDefinition:
    type: Kubernetes
    spec: {}
  EOT
}

# links the gitops cluster(s) to the "demo" environment - required by the
# gitops-enabled deployment stage in the sync + PR pipelines.
resource "harness_platform_environment_clusters_mapping" "demo" {
  org_id     = var.org_id
  project_id = harness_platform_project.this.id
  env_id     = harness_platform_environment.demo.id
  identifier = "demo"

  dynamic "clusters" {
    for_each = var.clusters
    content {
      identifier       = harness_platform_gitops_cluster.this[clusters.key].identifier
      name             = clusters.key
      agent_identifier = var.gitops_agent_id
      scope            = "PROJECT"
    }
  }
}

resource "harness_platform_gitops_applicationset" "example_apps" {
  depends_on = [
    harness_platform_gitops_cluster.this,
    harness_platform_gitops_app_project_mapping.default,
    harness_platform_gitops_app_project.default,
    harness_platform_gitops_repository.gitops_sample,
  ]

  org_id     = var.org_id
  project_id = harness_platform_project.this.id
  agent_id   = var.gitops_agent_id
  upsert     = true

  applicationset {
    metadata {
      name      = "python-app"
      namespace = "gitops-agent"
    }

    spec {
      go_template = true

      generator {
        clusters {
          enabled = true
        }
      }

      template {
        metadata {
          name = "{{.name}}-python-app"
          labels = {
            "harness.io/serviceRef" = harness_platform_service.python_app_gitops.id
            "harness.io/envRef"     = harness_platform_environment.demo.id
          }
        }

        spec {
          project = "default"

          source {
            repo_url        = harness_platform_repo.gitops_sample.git_url
            path            = "gitops-sample-app/charts/Python-App"
            target_revision = "main"

            helm {
              parameters {
                name  = "ingress.enabled"
                value = "false" # no ingress controller in this lab's kind clusters
              }
            }
          }

          destination {
            server    = "{{.server}}"
            namespace = "python-app"
          }

          sync_policy {
            automated {
              prune     = true
              self_heal = true
            }
            sync_options = ["CreateNamespace=true"]
          }
        }
      }
    }
  }
}

# standard CD pipeline: a gitops-enabled deployment stage using the native
# GitOpsSync step to force an immediate sync of every registered spoke
# cluster's app generated by the appset above.
resource "harness_platform_pipeline" "gitops_sync" {
  depends_on = [harness_platform_gitops_applicationset.example_apps, harness_platform_environment_clusters_mapping.demo]

  name       = "sync gitops apps"
  identifier = "sync_gitops_apps"
  org_id     = var.org_id
  project_id = harness_platform_project.this.id
  tags       = ["source:opentofu"]

  yaml = templatefile("${path.module}/templates/pipelines/gitops_sync.yaml.tmpl", {
    ORG_ID        = var.org_id
    PROJECT_ID    = harness_platform_project.this.id
    PIPELINE_NAME = "sync gitops apps"
    PIPELINE_ID   = "sync_gitops_apps"

    SERVICE_ID     = harness_platform_service.python_app_gitops.id
    ENVIRONMENT_ID = harness_platform_environment.demo.id
    CLUSTER_IDS    = [for k in keys(var.clusters) : harness_platform_gitops_cluster.this[k].identifier]

    APPLICATIONS = [
      for name in keys(var.clusters) : {
        agentId         = var.gitops_agent_id
        applicationName = "${name}-python-app"
      }
    ]
  })
}
